### ISSUE TITLE
Set batch value to 1.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [yownas/seed_travel#11]
The seed travel doesn't work with any batch number above 1. If possible, can the script ensure it only runs with a value of 1, or at least warn that it isn't set to 1 before creating all of the images and erroring with:

Exception: Moviepy: ImageSequenceClip requires all images to be the same size

**Comment by yownas** [comment]
Fixed in https://github.com/yownas/seed_travel/commit/a67864c490c2479c61a5ef2d5854b6d87a09e578

**Comment by jacksoncafazzo** [comment]
I had the same problem, even though the batch count was set to 1. After setting the batch size to 1 everything worked perfectly. Maybe others will have my problem. Really cool script, thank you for sharing!

**Comment by yownas** [comment]
Oh, sorry. I was thinking of "Batch count". Well, now both batch count and size is forced to 1.
