### ISSUE TITLE
Question regarding using higher res images

### ISSUE THREAD

**Issue by cvar66** [yownas/seed_travel#12]
When using seed travel with img2img, higher res image outputs above 512 x 512 slows down the rate of change from seed to seed and the changes are much more subtle. Images at 512 that would change drastically barely change at all at 1024. Would be nice if there was away to make images change more drastically at higher res like they do at 512.

**Comment by yownas** [comment]
Not sure how to change this, apart from lowering the step count.

Changing the noise generated from the seed would only lead to having to change the next noise as well. And none of them would match up with the image you would get normally.

 But if anyone has an idea how to implement some kind of "Amplify noise" thingy I'd be glad to add it.
