### ISSUE TITLE
Travel from initial seed via untargeted accumulating seed variation?

### ISSUE THREAD

**Issue by Wurrkop** [yownas/seed_travel#13]
Hello! 

Thank you for making this script :)

I have a question/suggestion:

If im understading how seeds affect the generation then slightly changing the seed number should cause slight changes of the output.

Is there an easy way to start generating from a seed, automatically add or detract from the seed number, then generate from that, and repeat?

With settings for variation strenght and the target number of steps it would be outputting whatever it comes up with from the promps/seed, rather than aiming to go to a specific seed.

**Comment by yownas** [comment]
Hi,

Seeds are a bit confusing. They are only used to generate the initial "noise" that then gets refined into an image. Adding/subtractring to a seed doesn't make much sense. Seed 1 is a completely different noise compared to seed 2, seed 10 isn't closer to seed 11 than it is seed 100000.

What this script does is that is takes two, completely different initial noises (derived from two seeds) and then interpolate between them.

...and if you give it more seeds, it will start interpolating towards that noise, and the next and so on.

So, in a way it does what you describe, it outputs whatever it comes up with while it is interpolating from one noise to the other.
