### ISSUE TITLE
error moviepy python module not installed. Will not be able to generate video.

### ISSUE THREAD

**Issue by UnaiGar** [yownas/seed_travel#14]
hello good morning, I wanted to ask how to install the moviepy module in python, I followed the manual, I have several questions when I download from github the master, where should I put the folder that I unzip? in the directory C: where is python or where I have the stable diffusion? the installation command I launch it from cmd or from Git Bash or from python console? when i launch comand for install moviepy the cmd show me this.

C:\Program Files\Python310\moviepy-master>python setup.py install
running install
C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\Python310\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\Python310\\Lib\\site-packages\\test-easy-install-4724.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\Python310\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.pypa.io/en/latest/deprecated/easy_install.html

Please make the appropriate changes for your system and try again.

BUT i launch the same in CMD like root and show me this:

C:\Program Files\Python310\moviepy-master>python setup.py install
running install
C:\Program Files\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
C:\Program Files\Python310\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing moviepy.egg-info\PKG-INFO
writing dependency_links to moviepy.egg-info\dependency_links.txt
writing requirements to moviepy.egg-info\requires.txt
writing top-level names to moviepy.egg-info\top_level.txt
reading manifest file 'moviepy.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENCE.txt'
writing manifest file 'moviepy.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\moviepy
copying build\lib\moviepy\video\tools\cuts.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\drawing.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\interpolators.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\segmenting.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\subtitles.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\tracking.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\tools\__init__.py -> build\bdist.win-amd64\egg\moviepy\video\tools
copying build\lib\moviepy\video\VideoClip.py -> build\bdist.win-amd64\egg\moviepy\video
copying build\lib\moviepy\video\__init__.py -> build\bdist.win-amd64\egg\moviepy\video
copying build\lib\moviepy\__init__.py -> build\bdist.win-amd64\egg\moviepy
byte-compiling build\bdist.win-amd64\egg\moviepy\audio\AudioClip.py to AudioClip.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\video\tools\subtitles.py to subtitles.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\video\tools\tracking.py to tracking.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\video\tools\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\video\VideoClip.py to VideoClip.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\video\__init__.py to __init__.cpython-310.pyc
byte-compiling build\bdist.win-amd64\egg\moviepy\__init__.py to __init__.cpython-310.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying moviepy.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying moviepy.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying moviepy.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying moviepy.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying moviepy.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist\moviepy-2.0.0.dev2-py3.10.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing moviepy-2.0.0.dev2-py3.10.egg
Removing c:\program files\python310\lib\site-packages\moviepy-2.0.0.dev2-py3.10.egg
error: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: 'c:\\program files\\python310\\lib\\site-packages\\moviepy-2.0.0.dev2-py3.10.egg'

C:\Program Files\Python310\moviepy-master>

I think after this, the installation is succesfully. but stable diffusion CMD show me "moviepy python module not installed. Will not be able to generate video."

Please could yo help me. thanks

**Comment by yownas** [comment]
You should not install it manually, the webui wants all its python modules in a venv.

If you add the line "moviepy==1.0.3" in the file requirements_versions.txt in the stable-diffusion-webui folder, and start webui-user.sh it should download everything it needs automatically.
