### ISSUE TITLE
[Feature Request] Add an optional start and end 'freeze' frame

### ISSUE THREAD

**Issue by ImagineerNL** [yownas/seed_travel#19]
Great tool and works nicely.

would be nice if you included an optional start and end freeze.
This could be done by re-using the first created picture and then repeat that for x frames (or x seconds) before starting and doing the same with the last picture.

**Comment by yownas** [comment]
I hope this was what you asked for. :) I've added so you can set a number of frames that will work as "lead in/out".

**Comment by ImagineerNL** [comment]
Yes it is!
Thank you very much!
