### ISSUE TITLE
USER_EXAMPLES/submission for seed travel

### ISSUE THREAD

**Issue by ClashSAN** [yownas/seed_travel#22]
I saw you had a USER_EXAMPLES.md in shift attention, so I wanted to contribute! It's in gif format. The problem is, it was so big so I couldn't display it on a message!

https://github.com/ClashSAN/bloated-gifs/blob/main/seedtravel.gif

It will display on an .md page though:

```
<details><summary>example: (Click to expand:)</summary>
<img src="https://github.com/ClashSAN/bloated-gifs/blob/main/seedtravel.gif" width="512" height="512" />
</details>
```

a window to space, synthwave style

Negative prompt:

Sampling method: DDIM Sampling Steps: 8 CFG Scale: 7

Seed: 1,2,3,4,5,6

Script: seed travel

Steps: ? FPS: 30

I may or may not have added ",trending on artstation" to the end. The original video was 36 seconds.
https://user-images.githubusercontent.com/98228077/192487018-06e1b86a-8763-4e8c-906b-273754f161cd.mp4

**Comment by yownas** [comment]
Nice animation. :) I added a USER_EXAMPLES.md to this repo as well.
