### ISSUE TITLE
BUG: SCRIPT WONT RUN with any sampler UNLESS I CHECK THIS BOX.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [yownas/seed_travel#26]
I GET THIS ERROR - AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index'

DOES NOT MATTER WHICH SAMPLER I USE, NONE WORKS until i CHECK THIS BOX - euler, euler a, ddims, heun, none works until i do this,,,,

![Screenshot 2022-12-07 225747](https://user-images.githubusercontent.com/112510084/206345479-27a78a12-d253-4014-995d-cc44a666a5b2.jpg)

**Comment by yownas** [comment]
Sorry for the late reply. It seems like you are using an old version of the seed_travel.py script. AUTO changed the way samplers were stored and that broke the way I checked. You should be able to update it by just copying the seed_travel.py file from this repo. Or if you installed it through the Extensions tab in the webui, just click " Check for updates" and then "Apply and restart UI".

The "Number of frames for lead in/out" is just the amount of frames to be padded with a static image at the start and ending of the video. So you'll get a short pause before the video ends.

The video on the repo page is very old,, it uses the v1.4 model and has an old ui. But some tips on how to get smooth animations is first of all to have lots of steps, maybe 50 to 100. More steps will make it move slower/smoother. Another things is to not set a too high CFG Scale, giving the AI a little more freedom when drawing things.

And most important of all, some Samplers doesn't work well with variation seeds. (Which is what my script uses). That is why "Euler A" is disabled by default.  Traveling between only 2 seeds work fine, it is when you have 3 or more seeds that it will fail and "skip" as it reach one seed and starts moving towards the next.

(Of course, none of these are hard rules. If you want to use Euler A, with a super high CFG Scale, go for it. :) I mainly made this script to help people play around with seeds and explore what they can do. As long as people have fun, I'm happy.)
