### ISSUE TITLE
not consistent travel across multiple seeds

### ISSUE THREAD

**Issue by vsewall** [yownas/seed_travel#28]
for some reasone I have the same effect with model 2.1 and 1.5:

travel from one seed to another looks great, but when the second seed is reached, there is a sharp jump. and then it repeats with new pair of seeds

I figured out that seed1 with subseed2 weight=1 not equal seed2

but your example looks consistent with multiple seeds

**Comment by yownas** [comment]
Yes, this is a known issue. But I don't know if there is a good/simple way to fix it. Some of the samplers (like "Euler a") seem to only use the first seed for... something (not sure what), which makes it "jump" when you start from the next seed. Samplers that works well is Euler, LMS, Heun, DPM2 & DDIM (and possibly some of the new ones).
