### ISSUE TITLE
Available for cmdr2's UI?

### ISSUE THREAD

**Issue by IshanJ25** [yownas/seed_travel#29]
How can I use it with CMDR2's UI?
awesome project btw!

**Comment by yownas** [comment]
Unfortunately it can't be used directly. Extensions for auto1111's version are written in python while cmdr2 seem to use javascript to change the behaviour of the interface. ...and even if you could re-write it in javascript (which shouldn't be too hard), I don't think cmdr2 supports variation seeds (or subseeds) and adding support for that would probably not be very easy. :(

(Variation seeds are a way to give 2 different start seeds, generate "noise" from them and blend them according to whatever weight you asked for to get a new initial noise that will be the starting point when generating the image. )

**Comment by IshanJ25** [comment]
so there is no way to use this with cmdr2's UI?

**Comment by yownas** [comment]
Sorry, no.
