### ISSUE TITLE
Fast API support 

### ISSUE THREAD

**Issue by olegchomp** [yownas/seed_travel#30]
Will be great to add API endpoints, so scripts could be run with A1111 API requests

**Comment by yownas** [comment]
That would be nice. Unfortunately I don't know how to do that, it is a bit beyond my python skills. I tried to see if there were any other extensions that supported the API (that I could learn from), but couldn't find one.

**Comment by olegchomp** [comment]
Litte example that works 

```
from fastapi import FastAPI
import gradio as gr

import modules.script_callbacks as script_callbacks

def travel(demo: gr.Blocks, app: FastAPI):
    @app.post("/seed_travel/")
    async def start_travel(rnd_seed, seed_count):
        print(rnd_seed,seed_count)

script_callbacks.on_app_started(travel)
```

**Comment by vladmandic** [comment]
there is no clean way to add an api endpoint for an *optional* component.  
but you already **can** trigger script using txt2img or img2img api endpoints, just pass optional `script_name` as part of api request.

**Comment by olegchomp** [comment]
Thank you!
So another question, can you add please "output folder" parameter and save images in those. Because if i run extension with API, images doen't save anywhere. If i set "show images" in script, images come with API request, but it limits to 9-12 images, after response stuck and no give no output.

**Comment by vladmandic** [comment]
i'll figure something out, probably next week...

**Comment by vladmandic** [comment]
this issue can be closed as my pr was merged.
