### ISSUE TITLE
Feature Request: Support Upscaling before generating video.

### ISSUE THREAD

**Issue by Hellisotherpeople** [yownas/seed_travel#34]
Right now, for both this extension and for prompt travel, a user who wants to upscale their animation will need to individual (or in a batch) upscale each image and then will have to convert these images into an mp4 or .gif themselves. 

Maybe we should support allowing a user to do this in the UI before the final generated video. Besides, you'll be able to show off 8K animations really easily to motivate folks to use it!

**Comment by Hellisotherpeople** [comment]
Btw, the prompt travel author thought this was a great idea and implemented it less than 24 hours after I requested it from them: 
https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel/issues/12

Proves it shouldn't be hard to do.

**Comment by yownas** [comment]
Hi,
I took a quick look a how he did it in the prompt-traveler script and it didn't seem to complicated. At the moment I'm a but overwhelmed at work but I really like the idea and will try to add it this weekend if I manage to find some time.

**Comment by Hellisotherpeople** [comment]
One small request, can we set the scaling multiplier as high as 8 (or higher if it can go even further)? The regular upscaler supports going that high. I was hoping to do 4K videos Otherwise this is awesome and works perfectly!

**Comment by yownas** [comment]
Change the range to "0 to 8". Not sure why anyone would want to "upscale" the video to anything smaller than 1, but now they can if they want. :)

To get the new values you might need to edit (or remove) the lines in ui-config.json that says something in the line of "customscript/seed_travel.py/txt2img/Upscale ratio/maximum". These are safe to remove and will be recreated when you run the webui.

You can also change the values in ui-config.json if you want to be able to scale it higher than 8x.

(It will have a "minimum" as well, and the same values stored for img2img)
