### ISSUE TITLE
Is it possible to seed travel to another prompt?

### ISSUE THREAD

**Issue by DenisKen** [yownas/seed_travel#37]
I want to combine different seeds with different prompts.

**Comment by yownas** [comment]
No, not with this script.

But there are some others that might do what you are after.
https://github.com/yownas/shift-attention (Can be a bit tricky to make it do what you want.)
https://github.com/Kahsolt/stable-diffusion-webui-prompt-travel (Haven't tried this one.)
https://github.com/deforum-art/deforum-for-automatic1111-webui (This is the one people used to make music videos. I haven't played around with it a lot but it looks like it can do a lot of animation related things.)
