### ISSUE TITLE
TypeError: 'NoneType' object does not support item assigment

### ISSUE THREAD

**Issue by megamanenm** [yownas/seed_travel#4]
I'm copying the settings from the demo pic, but I'm just getting an error code when I try to run it: 
![image](https://user-images.githubusercontent.com/4620182/191622568-fd7d66ce-6cd2-41b6-a9df-5358fab9b068.png)

**Comment by d1agram** [comment]
I'm getting this error as well. Can you explain what you mean by updating AUTOMATTIC1111's webui and this script?
Do you mean redownloading it and editing the requirements_versions.txt and copying over the script file?

**Comment by yownas** [comment]
Hm. Still a bit weird that it failed. Oh well, if it works I guess there isn't much to fix. :)

By the way, if you installed the webui by downloading it with "git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git" you would be able to get all updates by just running "git pull" (in cmd in the stable-diffusion-webui folder)
