### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by bitshifter52** [yownas/seed_travel#41]
I followed the readme instructions and things are not working.

I used "https://github.com/yownas/seed_travel.git" in the extensions tab and it shows up in the list of installed extensions. I also added the line "moviepy==1.0.3" to "requirements_versions.txt". I tried the install: !pip install moviepy==1.0.3 and it doesn't work, stable-diffusion-webui does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found. 

When I search for pyproject.toml in the stable-diffusion-webui folder it appears in several places:
/stable-diffusion-webui/repositories/k-diffusion/pyproject.toml
/stable-diffusion-webui/extensions/sd-dynamic-prompts/pyproject.toml
/stable-diffusion-webui/venv/lib/python3.9/site-packages/spacy/tests/package/pyproject.toml
/stable-diffusion-webui/repositories/xformers/third_party/cutlass/tools/library/scripts/pycutlass/pyproject.toml

A search for setup.py in the stable-diffusion-webui folder returns too many instances to list here.

Now when I run ./webui.sh I receive the following messages:
Launching Web UI with arguments: --opt-split-attention --xformers
Error loading script: seed_travel.py
Traceback (most recent call last):
  File "/home/{whoami}/stable-diffusion-webui/modules/scripts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/home/{whoami}/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/robert/stable-diffusion-webui/scripts/seed_travel.py", line 8
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

At this point I don't know how to proceed - so any suggestions will be appreciated.

**Comment by yownas** [comment]
If you installed ir through the extensions tab there is no need to add anything to requirements_versions.txt or install by hand. setup.py is used by the webui to install things, nothing you should need to run.

I'm a little but confused, it looks like you have it installed in the scripts folder, but it should have ended up under extensions.

I think the best thing would be to remove seed_travel.py from the scripts folder. And then install it from the extensions-tab; click Available, then Load from, search for "seed_travel" and click Install.

**Comment by bitshifter52** [comment]
Thanks for the response, I'll try your suggestion and see what happens.

**Comment by neggles** [comment]
Seems `imageio-ffmpeg` is required for moviepy to work properly; even after installing ffmpeg on an Ubuntu 22.04 image (docker container) the `import moviepy.video.io.ImageSequenceClip as ImageSequenceClip` line fails

Looking again this may not actually be directly related to bitshifter52's issue 😅 but it *has* been causing me trouble...
