### ISSUE TITLE
moviepy obsolete dependencies causing errors

### ISSUE THREAD

**Issue by vladmandic** [yownas/seed_travel#43]
`moviepy` requires `decorator` **4.x**, but when installing some other libraries required by stable diffusion they update `decorator` to **5.1** which is not compatible with `moviepy` and causes strange runtime errors in `ffmpeg_writer.py`  

unfortunate reality is that `moviepy` seems to be abandoned - it hasn't been updated since 05/2020, nearly 3 years  

big suggestion is to remove `moviepy` as dependency and just use `ffmpeg` directly  
it's not that hard to do, and it's a much more stable solution

**Comment by yownas** [comment]
I had a feeling there was a good reason no other extension seemed to use it. :) Yes, that is definitely worth looking into.

**Comment by vladmandic** [comment]
if it helps, feel free to copy from <https://github.com/vladmandic/sd-extension-steps-animation/blob/main/scripts/steps_animation.py>

**Comment by yownas** [comment]
Finally dared to rip off the bandaid, ffe0553c59e91067ebf1e4fc7ad85ca9c870bf57
