### ISSUE TITLE
Slowdown generation close to main seeds

### ISSUE THREAD

**Issue by Meru** [yownas/seed_travel#46]
Since my misunderstanding of things evolved into a feature request, I figured I might as well make a proper entry here.

My proposal is to implement a feature (or a couple of features) similar to Easy Ease, Ease In, Ease out in After effects.
The idea is that instead of linearly scaling from one seed to another, user would be able to select a pre-defined and/or custom curve that will make morphing animation faster at the beginning and slower at the end, or vice-versa, or both. Perhaps this can be better illustrated with the following image: 
![image](https://user-images.githubusercontent.com/2729827/227233706-df486206-38df-4bab-b4ab-2ade9eaccc51.png)

Another idea is to make an actual PAUSE at the specified seeds. But since simply duplicating an image is not very entertaining, perhaps an additional value X can be added that will instruct the script to sit on the main seed for some time (Y value, selectable) but deviate randomly forwards and backwards (and sideways if you can :D) by a maximum of X steps, where X is a value from 0 to 1. With 0 being equal to repeated frames, 1 equal to insane ugly randomness and 0.1 - 0.3 - probably a usable range.
So after doing this for a specified time (Y), the process would continue traveling to the next seed as before.

**Comment by yownas** [comment]
Maybe something like this for "easy ease in"?

https://www.wolframalpha.com/input?i=graph+%281-cos%28x%5Es*pi%29%29%2F2+from+0+to+1%2C+s%3D3

That way a strength of 3 would keep almost a static image half the way and then move over to the second seed. Setting s=1 would give you almost the same effect as in loopback. (Anything below 1 and above 3.14 (pi) would make things weird.)

**Comment by yownas** [comment]
Closing this. But if people still want to suggest curves or changes, feel free to post here.
