### ISSUE TITLE
Interview

### ISSUE THREAD

**Issue by 1busyguy** [yownas/seed_travel#47]
I am part of a large Generative AI project working with some of the top companies in the industry.  Personally I use Stable Diffusion to make art and wild video creations. I would like to interview you for our newsletter and share with people what you do. Would you be interested?  The site I am part of is called lore.com

**Comment by yownas** [comment]
Sorry for the late reply...
I'm literally a nobody when it comes to Stabel Diffusion, but if you want to have a quick chat, sure. :)

**Comment by 1busyguy** [comment]
Even people that think they are nobody are truly somebody, they just have
to realize it!
Do you have any time this week? and what time zone are you in?

Thanks
Jim

**Comment by yownas** [comment]
I should be able to find some time. :)
I'm in Central European Time, you can reach me at yownas@gmail.com
