### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by kawaiidesuu01** [yownas/seed_travel#48]
I generate 4 images but the extension only works with one

**Comment by kawaiidesuu01** [comment]
before I generated 4 images subsequently I put their seed in the destination field, I chose the number of steps (usually 40) and the extension generated 40 frames based on all 4 images, instead now I do the same procedure I did before but the 40 frames I get are based on only one of the 4 images.

**Comment by yownas** [comment]
Not sure what could be wrong. I wonder if you accidentally checked/used an option that you didn't mean to. Please double check that You haven't checked "Use random seeds". And that "Compare paths" and "Bump seed" isn't used.

**Comment by kawaiidesuu01** [comment]
Maybe there is something wrong with SSIM min threshold value, now I have it at 75
