### ISSUE TITLE
Save extra status info bug?

### ISSUE THREAD

**Issue by Meru** [yownas/seed_travel#49]
Basically when we have "Save extra status info" option on, script produces some random results.
1st image is missing
last image is present
in-between - it travels to some other seeds, not the one we selected. compared with commit a72c836c57d9c87259c3629ed9b15ff2732f0659

**Comment by yownas** [comment]
I'll check. I did some changes to how random seeds are handled, maybe I managed to mess something up there.

**Comment by yownas** [comment]
Think it is fixed now. It was a really silly mistake I've made. I hope it didn't cause too much problems.

**Comment by Meru** [comment]
could it be related to #48?

**Comment by Meru** [comment]
Did some tests, Now the output seem to be identical to what we had before. Thanks! Closing this.
