### ISSUE TITLE
Error loading script: seed_travel.py

### ISSUE THREAD

**Issue by VirtuallyOrange** [yownas/seed_travel#5]
After updating both AUTOMATIC1111's webui and this script this error pops up, if I start the webui-user.bat via Miniconda 3.
It also doesn't appear in the dropdown menu anymore (I'm assuming because it didn't load at all.
I updated both again 10 minutes before commiting this issue to check if it is still happening.

If I use an older version of seed_travel.py it works fine.
![image](https://user-images.githubusercontent.com/114165880/191770118-8a431167-8eab-43e1-89cb-164b5f3fe258.png)

**Comment by yownas** [comment]
Oh, I think you downloaded the html-page of the script.

Try this link instead: https://raw.githubusercontent.com/yownas/seed_travel/main/scripts/seed_travel.py

**Comment by VirtuallyOrange** [comment]
So this is how it feels to be an idiot.
Thank you!

**Comment by yownas** [comment]
You are not the first. :) https://www.youtube.com/watch?v=MreyOrYItr4
