### ISSUE TITLE
ERROR: Failed generating video

### ISSUE THREAD

**Issue by ParadoxVal** [yownas/seed_travel#51]
I am using auto1111 webui. And I get ERROR: Failed generating video, whenever I use the script. I get the individual frames just no video

**Comment by ParadoxVal** [comment]
I was able to resolve my issue, I had to install run "pip install moviepy=1.0.3".
Using the terminal in webui folder
 `
source venv/bin/activate
pip install moviepy==1.0.3
`

**Comment by yownas** [comment]
Sorry, I really should move from moviepy to imageio. I hope it didn't cause you too many problems.

**Comment by yownas** [comment]
Decided to finally ditch moviepy. ffe0553c59e91067ebf1e4fc7ad85ca9c870bf57

No more moviepy problems, lets hope imageio doesn't have new ways to break things. :)
