### ISSUE TITLE
[Request] Change CFG scale

### ISSUE THREAD

**Issue by Fllamber** [yownas/seed_travel#53]
Have a way to change the CFG scale for each seed. Can this be implemented?

**Comment by yownas** [comment]
I guess you technically could add it, but it would clutter up the ui a lot and break things for people who use the api.

But, I think it might be easier to add to https://github.com/yownas/shift-attention ... I'll do some tests.

**Comment by yownas** [comment]
Added CFG scale changing to shift-attention (not seed travel, still not sure how to do it without breaking a lot of other things). This is an animation of "cat" going from CFG Scale 7 to CFG Scale 0. Using the prompt:

cat THEN(cfg=0)

https://user-images.githubusercontent.com/13150150/234969936-c47b8ea5-e411-47bd-8da9-67b573239f72.mp4

**Comment by Fllamber** [comment]
Wow, that was fast.
I personaly imagined a 'scripting language' like the plugin "Prompts from file or textbox" where you specified line by line `--prompt` and add `--cfg`. 
It could aslo be in the `Destination seeds` box, you put a bracket like `1 [cfg:0], 2 [cfg:7]` 

 I will try that plugin and also try an API route and see were things go. Thanks.
